//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAS.Panel.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public int Id { get; set; }
        public int SubscriptionId { get; set; }
        public string RequestHeader { get; set; }
        public string ResponseHeader { get; set; }
        public string ResponseBody { get; set; }
        public Nullable<short> StatusCode { get; set; }
        public string URI { get; set; }
    
        public virtual Subscription Subscription { get; set; }
    }
}
