//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAS.Panel.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachmentFile
    {
        public System.Guid Id { get; set; }
        public int ItemId { get; set; }
        public Nullable<byte> AttachmentTypeId { get; set; }
        public string FileType { get; set; }
        public string FileName { get; set; }
        public byte[] FileContent { get; set; }
        public System.DateTime InsertDateTime { get; set; }
    
        public virtual AttachmentType AttachmentType { get; set; }
    }
}
