//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAS.Panel.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Subscriptions = new HashSet<Subscription>();
        }
    
        public int Id { get; set; }
        public byte CustomerTypeId { get; set; }
        public int RequestId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string IdentityNo { get; set; }
        public Nullable<int> BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public string NationalCode { get; set; }
        public string NationalId { get; set; }
        public string EducationDegree { get; set; }
        public string OrganizationPost { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string AgentName { get; set; }
        public string AgentMobile { get; set; }
        public string AgentEmail { get; set; }
        public string AgentOrganizationPost { get; set; }
        public string ActivityType { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public Nullable<bool> HasTax { get; set; }
        public System.DateTime InsertDateTime { get; set; }
    
        public virtual CustomerType CustomerType { get; set; }
        public virtual Request Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscription> Subscriptions { get; set; }
    }
}
