//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAS.Panel.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message()
        {
            this.Message1 = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public byte MessgaeTypeId { get; set; }
        public Nullable<int> ParentMessageId { get; set; }
        public string MessageTitle { get; set; }
        public int SenderUserId { get; set; }
        public int RecieverUserId { get; set; }
        public bool IsUrgent { get; set; }
        public System.DateTime SendDateTime { get; set; }
        public Nullable<System.DateTime> ReadDateTime { get; set; }
        public string MessageContent { get; set; }
        public Nullable<System.DateTime> DeleteDateTime { get; set; }
        public Nullable<int> DeleteUserId { get; set; }
    
        public virtual MessageType MessageType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Message1 { get; set; }
        public virtual Message Message2 { get; set; }
    }
}
