//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAS.Panel.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceInfo
    {
        public int Id { get; set; }
        public short ServiceId { get; set; }
        public byte LanguageTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Service Service { get; set; }
    }
}
