//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAS.Panel.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public Nullable<bool> SSLEnabled { get; set; }
        public Nullable<int> CreditThreshhold { get; set; }
        public Nullable<int> MinCreditForCoupon { get; set; }
        public Nullable<bool> EnableUnusedUsers { get; set; }
        public Nullable<bool> AutomaticInvoice { get; set; }
        public Nullable<byte> DefaultCurrencyId { get; set; }
        public Nullable<int> MaxCouponLive { get; set; }
        public Nullable<bool> ShowDescriptionOnInvoice { get; set; }
        public Nullable<int> AlloweMessageSendingTime { get; set; }
        public Nullable<int> NumberOfGridPaging { get; set; }
        public Nullable<bool> SignupEvent { get; set; }
        public Nullable<bool> StartServiceEvent { get; set; }
        public Nullable<bool> EndServiceEvent { get; set; }
        public bool EndOfCouponEvent { get; set; }
        public Nullable<bool> SubscriptionConfirmEvent { get; set; }
        public Nullable<bool> StartTrialEvent { get; set; }
        public Nullable<bool> EndTrialEvent { get; set; }
        public Nullable<bool> EndTrialComming { get; set; }
        public Nullable<bool> EndCoupon { get; set; }
        public Nullable<bool> EndServiceComming { get; set; }
        public Nullable<bool> EndService { get; set; }
        public Nullable<bool> PaymentDeadlineComming { get; set; }
        public Nullable<bool> PaymentDeadlineLeft { get; set; }
        public Nullable<bool> EndCouponComming { get; set; }
    }
}
